ALTER TABLE "profiles"
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "roles"
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "consultations"
  ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP;
